package uj.lab.fitnessapp.ui.theme

import androidx.compose.ui.graphics.Color

// WYGENEROWANE PRZEZ: https://material-foundation.github.io/material-theme-builder/

// Jasny Motyw
val primaryLight = Color(0xFF206A4E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA9F2CD)
val onPrimaryContainerLight = Color(0xFF005138)
val secondaryLight = Color(0xFF4D6357)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCFE9D9)
val onSecondaryContainerLight = Color(0xFF354B40)
val tertiaryLight = Color(0xFF3D6373)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC1E9FB)
val onTertiaryContainerLight = Color(0xFF244C5B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF5)
val onBackgroundLight = Color(0xFF171D1A)
val surfaceLight = Color(0xFFF5FBF5)
val onSurfaceLight = Color(0xFF171D1A)
val surfaceVariantLight = Color(0xFFDBE5DD)
val onSurfaceVariantLight = Color(0xFF404943)
val outlineLight = Color(0xFF707973)
val outlineVariantLight = Color(0xFFBFC9C1)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322E)
val inverseOnSurfaceLight = Color(0xFFEDF2EC)
val inversePrimaryLight = Color(0xFF8DD5B2)
val surfaceDimLight = Color(0xFFD6DBD6)
val surfaceBrightLight = Color(0xFFF5FBF5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5EF)
val surfaceContainerLight = Color(0xFFEAEFE9)
val surfaceContainerHighLight = Color(0xFFE4EAE4)
val surfaceContainerHighestLight = Color(0xFFDEE4DE)

// CiemnyMotyw
val primaryDark = Color(0xFF8DD5B2)
val onPrimaryDark = Color(0xFF003825)
val primaryContainerDark = Color(0xFF005138)
val onPrimaryContainerDark = Color(0xFFA9F2CD)
val secondaryDark = Color(0xFFB3CCBD)
val onSecondaryDark = Color(0xFF1F352A)
val secondaryContainerDark = Color(0xFF354B40)
val onSecondaryContainerDark = Color(0xFFCFE9D9)
val tertiaryDark = Color(0xFFA5CCDF)
val onTertiaryDark = Color(0xFF073543)
val tertiaryContainerDark = Color(0xFF244C5B)
val onTertiaryContainerDark = Color(0xFFC1E9FB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1511)
val onBackgroundDark = Color(0xFFDEE4DE)
val surfaceDark = Color(0xFF0F1511)
val onSurfaceDark = Color(0xFFDEE4DE)
val surfaceVariantDark = Color(0xFF404943)
val onSurfaceVariantDark = Color(0xFFBFC9C1)
val outlineDark = Color(0xFF8A938C)
val outlineVariantDark = Color(0xFF404943)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DE)
val inverseOnSurfaceDark = Color(0xFF2C322E)
val inversePrimaryDark = Color(0xFF206A4E)
val surfaceDimDark = Color(0xFF0F1511)
val surfaceBrightDark = Color(0xFF353B37)
val surfaceContainerLowestDark = Color(0xFF0A0F0C)
val surfaceContainerLowDark = Color(0xFF171D1A)
val surfaceContainerDark = Color(0xFF1B211D)
val surfaceContainerHighDark = Color(0xFF252B28)
val surfaceContainerHighestDark = Color(0xFF303632)


// Zostawiam w ramach kompatybilności gdybym gdzieś zapomniał zmienić nasze legacy kolory
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val backgroundColor = Color(0xFFDAD7CD)
// Zachowajmy specyficzne kolory aplikacji, ale dodajmy ich wersje dla ciemnego motywu
val favoriteColor = Color(0xFFbc4749)
val cardioColor = Color(0xFFA3B18A)
val strengthColor = Color(0xFF344E41)
val strengthColorLight = Color(0xFF344E41)
val strengthColorDark = Color(0xFF588157) // Ciemniejsza wersja dla dark theme
val darkGreen = Color(0xFF344E41)
val lovelyPink = Color(0xFFFF8FAB)

// Usuwamy stałe kolory tła i zastępujemy je referencjami do motywu
// val backgroundColor = Color(0xFFDAD7CD) // Usuń tę linię
val darkGreenLight = Color(0xFF344E41)
val darkGreenDark = Color(0xFF2D3E2D) // Ciemniejsza wersja dla dark theme
val goldColor = Color(0xFFFFBF00)